# GitHub Pages Configuration for PRIME Documentation
theme: jekyll-theme-minimal
title: PRIME Trading Intelligence
description: Professional Reinforcement Intelligence for Market Excellence
show_downloads: true
google_analytics: 

# Navigation
navigation:
  - title: Home
    url: /
  - title: Documentation
    url: /documentation
  - title: API Reference
    url: /api
  - title: Strategies
    url: /strategies
  - title: GitHub
    url: https://github.com/your-org/prime

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO
author: PRIME Team
twitter:
  username: primetrading
  card: summary_large_image

# Social
social:
  name: PRIME Trading
  links:
    - https://github.com/your-org/prime
    - https://twitter.com/primetrading